#!/bin/bash

CREDENTIALS="pi:raspberry"
MOTIONSTATUS_0=`/usr/bin/lwp-request -C $CREDENTIALS http://localhost:8080/0/detection/status`

# Log based variables
# Define the local logging directory, set the format for the logfile name, define the local logfile, get the last line of the current logfile,
# define the S3 logging directory, define the format of the timestamp used within the logs.
LOGDIR=/mnt/picam/logs
LOGNAME=`/bin/date +'%F'`
LOGFILE=$LOGDIR/$LOGNAME.log
TIMESTAMP=`/bin/date +'%F %R'`

#Make sure log directory exists.
if [ ! -d "$LOGDIR" ]; then
    /bin/mkdir -p $LOGDIR
fi

#Make sure there is at least an empty logfile.
if [ ! -f "$LOGFILE" ]; then
    /bin/touch $LOGFILE
fi

# If Motion is active...
if [[ "$MOTIONSTATUS_0" == *"ACTIVE"* ]]; then
    # Set the right text to back the current Motion status of STANDBY.
/usr/bin/lwp-request -C $CREDENTIALS "http://localhost:8080/0/config/set?text_right=%25Y-%25m-%25d+%25H%3A%25M%5CnSTANDBY" > /dev/null
# If Motion is paused...
elif [[ "$MOTIONSTATUS_0" == *"PAUSE"* ]]; then
    # Set the right text to back the current Motion status of PAUSED.
/usr/bin/lwp-request -C $CREDENTIALS "http://localhost:8080/0/config/set?text_right=%25Y-%25m-%25d+%25H%3A%25M%5CnPAUSED" > /dev/null
fi

# Update the log to show the time the event started.
/bin/echo "[$TIMESTAMP] Recording stopped." >> $LOGFILE