#!/bin/bash

# AWS credentials are necessary for this script to work properly.
# The aws_credentials file may be stored anywhere, but I keep in etc/motion/ for the sake of keeping things together.
# The aws_credentials file should be an executable Bash script similar to the following:
#
# #!/bin/bash
# export AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXX
# export AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Make AWS credentials available to the AWS commands used in this script.
source /etc/motion/aws_credentials

# Define local and destination directory for the sync.
VIDEODIR=/mnt/picam/video
S3_VIDEODIR=s3://home.fisher/picam/video

# Test if the internet is reachable
/usr/bin/wget --quiet --spider http://google.com
if [ "$?" = 0 ]; then
    # Sync videos to S3
	/usr/local/bin/aws s3 sync $VIDEODIR $S3_VIDEODIR
fi

